# Generated by Django 4.2.1 on 2023-05-31 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_subtitle_id', models.CharField(max_length=255)),
                ('mission_type', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('score', models.FloatField()),
                ('difficulty', models.FloatField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evaluation',
                'verbose_name_plural': 'Evaluation',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_subtitle_id', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('attempt_times', models.IntegerField()),
                ('duration', models.FloatField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Record',
                'verbose_name_plural': 'Record',
            },
        ),
        migrations.CreateModel(
            name='SubSubtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=255)),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('text', models.TextField()),
                ('condition', models.BooleanField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sub Subtitle',
                'verbose_name_plural': 'Sub Subtitle',
            },
        ),
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('youtube_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('youtube_name', models.CharField(max_length=255)),
                ('subtitle_name', models.CharField(max_length=255)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'YouTube Video',
                'verbose_name_plural': 'YouTube Videos',
            },
        ),
    ]
