# Generated by Django 4.2.1 on 2023-07-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_evaluation_last_update_time_record_last_update_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("youtube_id", models.CharField(max_length=255)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("last_update_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Bookmark",
                "verbose_name_plural": "Bookmark",
            },
        ),
    ]
