# Generated by Django 4.2.1 on 2023-08-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_weeklytask_rename_task_dailytask_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailytask",
            name="isFinish",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dailytask",
            name="total",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="weeklytask",
            name="isFinish",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="weeklytask",
            name="total",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
