# Generated by Django 4.2.1 on 2023-08-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_dailytask_isfinish_dailytask_total_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="last_update_time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="dailytask",
            name="last_update_time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="evaluation",
            name="last_update_time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="last_update_time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="subsubtitle",
            name="last_update_time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="weeklytask",
            name="last_update_time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="youtube",
            name="last_update_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
