# Generated by Django 4.2.1 on 2023-09-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_alter_bookmark_last_update_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInformation",
            fields=[
                ("user_id", models.IntegerField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=255)),
                ("user_email", models.CharField(max_length=255)),
                ("user_password", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="bookmark",
            name="user_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dailytask",
            name="user_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="evaluation",
            name="user_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="record",
            name="user_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subsubtitle",
            name="user_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="weeklytask",
            name="user_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="youtube",
            name="user_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
