# Generated by Django 4.2.1 on 2023-09-27 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_delete_userinformation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="youtube",
            name="user_id",
        ),
    ]
